DIP-32: Email Welcome Packs with Testnet Tokens for Workshops at DEVCon(nect)
efdevcon/DIPs pull request #123
Opened 2023-09-29 14:14 UTC by 0xkkonrad

## Description

## Related DIP issue

## Checklist
 * [x ] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [ x] syntax check
 * [x ] filename is DIP-X.md (with X being the correct DIP number)
 * [ x] header contains (in this order)
   * [x ] DIP
   * [x ] Title
   * [x ] Status
   * [x ] Themes
   * [x ] Tags
   * [x ] Authors
   * [x ] Resources Required (optional)
   * [x ] Discussion (with link to devcon forum)
   * [x ] Created (in the format year-month-day e.g 2020-4-20)
 * [ x] contains these sections:
   * [x ] Abstract
   * [ x] Rationale
   * [ x] Implementation
   * [ x] Operational Requirements & Ownership
 * [ x] PR title prefixed with DIP-X

2023-10-09 15:10 UTC, ligi requested changes
Thanks for the proposal - just some small nits - formally only the Rationale is missing
We will discuss it later this week (Thursday)

2023-10-09 15:10 UTC, ligi commented on DIPs/DIP-32.md
> +
```suggestion
```

2023-10-09 15:10 UTC, ligi commented on DIPs/DIP-32.md
> +4. Helping the DevCon(nect) temas use the new technology.
```suggestion
4. Helping the DevCon(nect) teams use the new technology.
```

2023-10-11 22:46 UTC, vb7401 commented
It may also be worth a collaboration with emailwallet.org team, a group funded by EF's PSE! This way the ticket email can directly be the receiver of the test token.

2023-10-12 12:46 UTC, ligi commented
@vb7401 can you elaborate how the collaboration would work on a technical level?

2023-10-12 13:06 UTC, vb7401 commented
I'm not a full expert, just a friend/fan of that team haha. From my understanding, they are building a smart contract wallet for arbitrary email addresses `email@domain.com`, where transferring tokens is gated by sending an email from `email@domain.com` with the specified action. This works because each email comes with a DKIM signature from the mailserver, which can then be verified on-chain cheaply using a ZKP, from which the action specified (sending money, sending an NFT) can be authorized.

It may be too early stage for them to support the specific types of test tokens this proposal needs, but roughly I am imagining that these tokens can directly be given to the smart contract wallets for each of the pretix emails instead of doing a flow with a claim link + sending them to another wallet. And in general, I am very bullish on emailwallet.org long-term being the right medium for "token airdrop to ticket holder" solutions, especially in communities that are less web3 focused/pilled!

2023-10-12 14:09 UTC, ligi commented
I would need to dig into email-wallet from the surface I have concerns wrt centralisation and readyness - just wanted to try it out and got this:
![image](https://github.com/efdevcon/DIPs/assets/111600/6b5aca36-1c34-4bdc-9679-49acc7a9500d)

So I think for DEVConnect we should go with peanut

2023-10-12 16:42 UTC, vb7401 commented
Yep, they're working on shipping a lot of the functionality for Devconnect, so it might be too difficult to make everything work out. Perhaps for a future Devcon 😃🤞

2023-11-11 18:47 UTC, ligi commented
Sorry but we went with the PCDPass faucet solution in the end: https://twitter.com/_pk910_/status/1721472568765345955

Your solution is great - but we want to encourage users to use PCDPass

2023-11-11 18:47 UTC, closed without merging