DIP-38 first draft - Anon Aadhaar zk proof for Indian discounts for Devcon tickets
efdevcon/DIPs pull request #139
Opened 2024-06-20 00:47 UTC by Meyanis95

2024-06-20 06:36 UTC, wslyvh requested changes
Hi @Meyanis95 - this is great. Thanks for the DIP

Can you also post this to our [forum](https://forum.devcon.org/c/dip-discussion/6) and add the link as a discussions header here

2024-06-20 06:36 UTC, wslyvh commented on DIPs/DIP-38.md
> +DIP: 38
Can you update to 40
38 and 39 are already opened as other PRs

2024-07-11 13:07 UTC, ligi approved these changes

2024-07-11 13:19 UTC, ligi approved these changes

2024-07-11 13:19 UTC, merged