Proposing ticket system with prior implementations
efdevcon/DIPs pull request #14
Opened 2020-08-14 12:40 UTC by colourful-land

Forum Discussion is here: https://forum.devcon.org/t/attestation-based-ticketing-system-that-is-managed-by-ethereum-smart-contracts-and-integrated-with-pretix-re-rfp-1-onchain-ticketing/54

2020-08-20 10:35 UTC, ligi commented on DIPs/DIP-6-Ticket.md
> +A. Yes, the ticket can be used to check-in with out internet. This was one of the key requirements for the implemetnations for FIFA and UEFA. However, internet will be needed to access the advanced D
```suggestion
A. Yes, the ticket can be used to check-in with out internet. This was one of the key requirements for the implementations for FIFA and UEFA. However, internet will be needed to access the advanced DAPP features offered by the ticket such as voting.
```

2020-08-20 10:35 UTC, ligi commented on DIPs/DIP-6-Ticket.md
> +In 2019, we also worked tordwards implementing EDCON 2020 event tickets on blockchain. Again, the app and tickets were ready, but thanks to the pandemic, the event got cancelled 😭😭😭)
```suggestion
In 2019, we also worked towards implementing EDCON 2020 event tickets on blockchain. Again, the app and tickets were ready, but thanks to the pandemic, the event got cancelled 😭😭😭)   
```

2020-08-20 10:35 UTC, ligi commented on DIPs/DIP-6-Ticket.md
> +The next full fledged implmentation was in 2019, with Shankai Sports for tokenising EURO Championship 2020 VIP event tickets, with integrated hospitality passes([App](https://apps.apple.com/us/app/sh
```suggestion
The next full fledged implementation was in 2019, with Shankai Sports for tokenising EURO Championship 2020 VIP event tickets, with integrated hospitality passes([App](https://apps.apple.com/us/app/shankai/id1492559481). The tickets were tokenised and the apps were ready to go, but the event got cancelled 😭😭😭)
```

2020-08-20 11:39 UTC, ligi requested changes
Thanks for the PR! Found some typos and please rename to DIP-6.md - maybe also consolidate the usage of Ethereum (currently lower case ethereum and upper case Ethereum are present)

2020-08-20 14:25 UTC, skylarweaver commented
Also, one more comment could you please change "DEVCON" to "Devcon" ? 

Better to differentiate from DEF CON ;-)

2020-08-30 06:35 UTC, colourful-land commented
> Thanks for the PR! Found some typos and please rename to DIP-6.md - maybe also consolidate the usage of Ethereum (currently lower case ethereum and upper case Ethereum are present)

Thanks & mentioned issues are addressed a few weeks ago but forgot to update PR.

2020-09-02 23:36 UTC, ligi commented
sorry for the delayed merge - we are still fleshing out the rough edges of this brand new process. Good thing is that we still have some time to DevCon ;-)
We now have a checklist and I will go through it - once all is checked we will merge.

 * [ ] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [ ] syntax check
 * [ ] filename is DIP-X.md (with X being the correct DIP number)
 * [ ] header contains (in this order)
   * [ ] DIP
   * [ ] Title
   * [ ] Status
   * [ ] Theme(s)
   * [ ] Tag(s)
   * [ ] Author(s)
   * [ ] Resources Required (optional)
   * [ ] Discussion-to (with link to devcon forum)
   * [ ] Created (in the format year-month-day e.g 2020-4-20)
 * [ ] contains these sections:
   * [ ] Abtract
   * [ ] Rationale
   * [ ] Implementation
   * [ ] Operational Reuirements & Ownership
 * [ ] PR title prefixed with DIP-X

2020-09-03 00:51 UTC, colourful-land commented
Requested changes made. Thanks

2020-09-03 01:22 UTC, ligi approved these changes

2020-09-03 01:22 UTC, merged