DIP-4120
efdevcon/DIPs pull request #151
Opened 2024-09-15 21:19 UTC by serg0x

## Description
Add DIP4120

## Related DIP issue
https://forum.devcon.org/t/tabletop-gaming-level-up-at-devcon/4120

## Checklist
 * [x] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [x] syntax check
 * [x] filename is DIP-X.md (with X being the correct DIP number)
 * [x] header contains (in this order)
   * [x] DIP
   * [x] Title
   * [x] Status
   * [x] Themes
   * [x] Tags
   * [x] Authors
   * [x] Resources Required (optional)
   * [x] Discussion (with link to devcon forum)
   * [x] Created (in the format year-month-day e.g 2020-4-20)
 * [x] contains these sections:
   * [x] Abstract
   * [x] Rationale
   * [x] Implementation
   * [x] Operational Requirements & Ownership
 * [x] PR title prefixed with DIP-X

2024-09-16 14:27 UTC, ligi requested changes
Thanks! But please let's stay sequential - use DIP-48

2024-09-16 20:06 UTC, serg0x commented
> Thanks! But please let's stay sequential - use DIP-48

Done!

2024-09-17 13:20 UTC, ligi requested changes

2024-09-19 20:35 UTC, serg0x commented
Thx for your comments @ligi; done!

2024-09-19 21:45 UTC, ligi approved these changes

2024-09-19 22:11 UTC, merged