DIP-49L: The Onchain CReator Hub
efdevcon/DIPs pull request #153
Opened 2024-09-18 21:36 UTC by isaaczaak

[DIP for The Onchain Creator Hub proposal at Devcon 2024](https://forum.devcon.org/t/sea-community-hub-proposal-the-onchain-creator-hub/4211/1)

## Checklist
 * [x] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [x] syntax check
 * [x] filename is DIP-X.md (with X being the correct DIP number)
 * [x] header contains (in this order)
   * [x] DIP
   * [x] Title
   * [x] Status
   * [x] Themes
   * [x] Tags
   * [x] Authors
   * [x] Resources Required (optional)
   * [x] Discussion (with link to devcon forum)
   * [x] Created (in the format year-month-day e.g 2020-4-20)
 * [x] contains these sections:
   * [x] Abstract - replaced with Summary
   * [x] Rationale
   * [x] Implementation
   * [x] Operational Requirements & Ownership - replaced with Team
 * [x] PR title prefixed with DIP-X

2024-09-25 10:51 UTC, ligi requested changes

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +-----Summary of Proposal-----
```suggestion
## Summary of Proposal
```

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +__Please answer questions below:__
```suggestion
## Team
```

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +-----Implementation-----
```suggestion
## Implementation
```

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +#### How would this community hub enhance attendee experience?
```suggestion
## Motivation & Rationale
```

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +#### How would this compliment the main programme that is happening at Devcon?
```suggestion
```

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +#### Why is this topic significant, and why is a community hub the best format to address it instead of a talk or workshop at the main conference?
```suggestion
```

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +**Why are we best suited to drive this community hub? What expertise do we offer in this topic?**
```suggestion
```

2024-09-25 10:51 UTC, ligi commented on DIPs/DIP-49.md
> +
```suggestion
```

2024-09-26 15:45 UTC, isaaczaak commented
i've committed all the requested changes, thanks @ligi !

2024-10-15 00:11 UTC, ligi commented
@isaaczaak ci is still failing please apply the other change

2024-10-15 00:11 UTC, ligi commented
or allow maintainers to commit to this branch

2025-01-28 11:22 UTC, closed without merging