Patch 3
efdevcon/DIPs pull request #155
Opened 2024-09-18 23:34 UTC by BrenPalav

## Description

## Related DIP issue

## Checklist
 * [ ] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [ ] syntax check
 * [ ] filename is DIP-X.md (with X being the correct DIP number)
 * [ ] header contains (in this order)
   * [ ] DIP
   * [ ] Title
   * [ ] Status
   * [ ] Themes
   * [ ] Tags
   * [ ] Authors
   * [ ] Resources Required (optional)
   * [ ] Discussion (with link to devcon forum)
   * [ ] Created (in the format year-month-day e.g 2020-4-20)
 * [ ] contains these sections:
   * [ ] Abstract
   * [ ] Rationale
   * [ ] Implementation
   * [ ] Operational Requirements & Ownership
 * [ ] PR title prefixed with DIP-X

2024-09-24 15:14 UTC, BrenPalav commented
@ligi could you help us with this conflict? We thought this DIP # has been used

2024-09-25 12:01 UTC, ligi requested changes
yes - 47 is used - you can use 54 as stated in your title - but also do not edit the README without a good reason

2024-10-15 00:17 UTC, ligi requested changes
Please do not edit DIP-0

2024-10-15 22:13 UTC, BrenPalav commented
@ligi what should I do? Create a new PR?

2024-10-15 23:13 UTC, ligi commented
no you can just change this PR to not edit this file

2024-10-15 23:13 UTC, ligi commented
but whatever is easiest for you - or I just do the change

2024-10-16 14:14 UTC, BrenPalav commented
@ligi I'd appreciate it if you could do it

2025-01-28 11:22 UTC, closed without merging