Devcon 5.1
efdevcon/DIPs pull request #16
Opened 2020-08-14 17:45 UTC by crisgarner

2020-08-20 11:44 UTC, ligi requested changes
Thanks for the PR - unfortunately DIP-6 was submitted before (the ticketing PR from alphawallet) - so please rename to DIP-9.md and change the DIP in the header.
otherwise LGTM

2020-08-20 11:44 UTC, ligi commented on DIPs/DIP-6.md
> +DIP: 6
```suggestion
DIP: 9
```

2020-08-20 22:29 UTC, crisgarner commented
@ligi Thanks! updated to 9

2020-08-20 22:30 UTC, ligi approved these changes

2020-08-20 22:31 UTC, ligi commented
@crisgarner thanks! LGTM to me now - after a second editor will look over it we should be good to merge

2020-08-27 14:49 UTC, ligi commented
sorry for the delay - we are still young in the process and currently some people are in holiday. Going through the new checklist (#22) now:

 * [x] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [x] syntax check
 * [ ] filename is DIP-X.md (with X being the correct DIP number)
 * [ ] header contains (in this order)
   * [ ] DIP
   * [ ] Title
   * [ ] Theme
   * [ ] Tags
   * [ ] Author
   * [ ] Resources Required
   * [ ] Discussion-to (with link to devcon forum)
   * [ ] Created
 * [ ] contains these sections:
   * [ ] Abtract
   * [ ] Rationale
   * [ ] Implementation
   * [ ] Operational Reuirements & Ownership
 * [ ] PR title prefixed with DIP-X

2020-08-27 14:54 UTC, merged