DIP-56: Social Stereo
efdevcon/DIPs pull request #166
Opened 2024-09-28 13:55 UTC by 0xPetra

# DIP-56: Social Stereo

## Description
Adding DIP-56: Social Stereo for Devcon 8
https://forum.devcon.org/t/dip-49-social-stereo/4354

## Related DIP issue

## Checklist
 * [x] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [x] syntax check
 * [x] filename is DIP-X.md (with X being the correct DIP number)
 * [x] header contains (in this order)
   * [x] DIP
   * [x] Title
   * [x] Status
   * [x] Themes
   * [x] Tags
   * [x] Authors
   * [x] Resources Required (optional)
   * [x] Discussion (with link to devcon forum)
   * [x] Created (in the format year-month-day e.g 2020-4-20)
 * [x] contains these sections:
   * [x] Abstract
   * [x] Rationale
   * [x] Implementation
   * [x] Operational Requirements & Ownership
 * [x] PR title prefixed with DIP-X

2024-10-16 12:22 UTC, ligi requested changes
This is super awesome! Just some minor changes and we can merge this - sorry for the latency in reviewing. Should also connect you to the music stage and the blockravers.

2024-10-16 12:22 UTC, ligi commented on DIPs/DIP-56.md
> +---
```suggestion
```

2024-10-17 02:24 UTC, ligi approved these changes

2024-10-17 02:25 UTC, merged

2024-10-17 03:14 UTC, 0xPetra commented
Thanks for reviewing ligi!

We brainstormed this with Alaska and Shakka, running the music stage. I know Manu from BLockRavers, but wasn't aware they were also involved. Amazing! 🔥

Which is the best place to create a group chat?