DIP-60: Solidity UFC - Solidity Programming Competition
efdevcon/DIPs pull request #170
Opened 2024-10-17 18:13 UTC by fiveoceans-dev

## Description
I am proposing a DIP-60 a coding event aiming to bring together solidity programmers.

## Related DIP issue

## Checklist
 * [ v ] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [ v ] syntax check
 * [ v ] filename is DIP-X.md (with X being the correct DIP number)
 * [ v ] header contains (in this order)
   * [ v ] DIP
   * [ v ] Title
   * [ v ] Status
   * [ v ] Themes
   * [ v ] Tags
   * [ v ] Authors
   * [ v ] Resources Required (optional)
   * [ v ] Discussion (with link to devcon forum)
   * [ v ] Created (in the format year-month-day e.g 2020-4-20)
 * [ v ] contains these sections:
   * [ v ] Abstract
   * [ v ] Rationale
   * [ v ] Implementation
   * [ v ] Operational Requirements & Ownership
 * [ v ] PR title prefixed with DIP-X

2024-10-18 00:38 UTC, ligi requested changes
Super nice proposal - just 2 nits in the comments.
Also wondering if it is legal to name it around UFC or if this is protected.
Maybe a more generic "Race" or something like this is safer. Need to consult legal with this.

2024-10-18 00:38 UTC, ligi commented on DIPs/DIP-60.md
> +Instances: [Devcon6]
```suggestion
Instances: ["Devcon7"]
```
this change - or you need a time machine and go back to bogota ;-)

2024-10-18 00:38 UTC, ligi commented on DIPs/DIP-60.md
> +Authors: Five (@fiveoceans_dev)
```suggestion
Authors: Five (@fiveoceans-dev)
```
github name assumed here

2024-10-18 06:38 UTC, ligi requested changes
In the screenshots it is still UFC not USC

2024-10-18 07:31 UTC, fiveoceans-dev commented
Thanks, I have removed all instances of the word 'UFC'.

2024-10-19 06:15 UTC, fiveoceans-dev reviewed
i pushed updates to removed all instances of the word ‘UFC’

2024-10-19 07:57 UTC, ligi approved these changes

2024-10-19 07:58 UTC, merged