Added DIP-12 which extends DIP-1
efdevcon/DIPs pull request #37
Opened 2020-10-22 12:00 UTC by raphabenoi

DIP-12 extends [CO2ken's original DIP-1](https://github.com/efdevcon/DIPs/blob/master/DIPs/DIP-1.md) and explains how contributions are collected and allocated to carbon projects using a DAO

2020-10-22 15:15 UTC, ligi requested changes
Thanks for the PR - just had a quick look and found a typo. Also my spell checker would be happy if we could also change amongst to among. But there both work - the other one is clearly a typo.
Will have a deeper look later - thanks for your work!

2020-10-22 15:15 UTC, ligi commented on DIPs/DIP-12.md
> +* [Medium post describing the project's Genesis (things have chaged since then)](https://medium.com/curve-labs/co2ken-genesis-74d7a1387ea1)
```suggestion
* [Medium post describing the project's Genesis (things have changed since then)](https://medium.com/curve-labs/co2ken-genesis-74d7a1387ea1)
```

2020-10-23 20:01 UTC, raphabenoi commented
Thanks for spotting the typo @ligi

2020-11-02 15:03 UTC, ligi approved these changes

2020-11-02 15:03 UTC, merged