Create DIP-14.md
efdevcon/DIPs pull request #42
Opened 2020-11-25 10:18 UTC by VMLVaske

2020-11-25 11:45 UTC, ligi requested changes

2020-11-25 11:45 UTC, ligi commented on DIPs/DIP-14.md
> +Offer the possibility to submit posters - either parallely during the call for "speaking slots" or specifically to those, whose talk submission got rejected.
```suggestion
Offer the possibility to submit posters - either parallelly during the call for "speaking slots" or specifically to those, whose talk submission got rejected. 
```

2020-11-25 11:46 UTC, ligi commented
* [ ] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [ ] syntax check
 * [ ] filename is DIP-X.md (with X being the correct DIP number)
 * [ ] header contains (in this order)
   * [ ] DIP
   * [ ] Title
   * [ ] Status
   * [ ] Theme(s)
   * [ ] Tag(s)
   * [ ] Author(s)
   * [ ] Resources Required (optional)
   * [ ] Discussion-to (with link to devcon forum)
   * [ ] Created (in the format year-month-day e.g 2020-4-20)
 * [ ] contains these sections:
   * [ ] Abstract
   * [ ] Rationale
   * [ ] Implementation
   * [ ] Operational Requirements & Ownership
 * [ ] PR title prefixed with DIP-X

2020-11-29 20:47 UTC, VMLVaske reviewed
Changed spelling

2020-11-30 00:43 UTC, ligi commented
Thanks. The last checkbox I am missing is the created header. Then editor-wise it is OK to merge.

2020-12-09 12:54 UTC, VMLVaske commented
Sorry for the delay! Added the creation-header-column :D

2020-12-09 13:22 UTC, ligi requested changes
Thanks & no worries.
Just bringing this to our standard format and then I would merge

2020-12-09 13:22 UTC, ligi commented on DIPs/DIP-14.md
> +Created: 25.11.2020
```suggestion
Created: 2020-11-25
```

2020-12-09 13:23 UTC, ligi approved these changes

2020-12-09 13:23 UTC, merged