Update DIP-3.md
efdevcon/DIPs pull request #78
Opened 2022-05-31 14:13 UTC by lucarioams

After our conversation with the Devcon team on 26th of May 2022, the decision was to re-fresh the DIP-3 in preparation to enable Devcon attendees to book their accommodation on-chain with Dai.

2022-06-01 20:14 UTC, ligi requested changes
Minor nits - otherwise LGTM

2022-06-02 06:40 UTC, lucarioams commented on DIPs/DIP-3.md
> +Winding Tree has been building decentralized solutions for the travel since 2017, currently focusing on building decentralized marketplaces, the first one being accommodation. In April 2022, we did o
yes thank for spotting it out, it is meant as ""for the travel industy"

2022-06-03 10:37 UTC, ligi requested changes

2022-06-03 10:37 UTC, ligi commented on DIPs/DIP-3.md
> +Winding Tree has been building decentralized solutions for the travel since 2017, currently focusing on building decentralized marketplaces, the first one being accommodation. In April 2022, we did o
```suggestion
Winding Tree has been building decentralized solutions for the travel industry since 2017, currently focusing on building decentralized marketplaces, the first one being accommodation. In April 2022, we did our Proof of Concept during Devconnect, nearly 100 room nights were booked via a smart contract on the gnosis chain and paid with xDai. Since then we have been building our protocol [Videre](https://github.com/windingtree/videre) that improves the capabilities, efficiency and privacy of the marketplace. We will be testing the [Stays](https://github.com/windingtree/win-stays) implementation of the protocol during the upcoming events of ETHBarcelona, ETHcc Paris, and Dappcon Berlin. 
```

2022-06-03 11:00 UTC, ligi commented on DIPs/DIP-3.md
> +The use of blockchain to decentralized travel marketplaces is not novel and has been thought about and worked for years, however, the return of travel after the pandemic, the progress on L2s and side
```suggestion
The use of blockchain to decentralized travel marketplaces is not novel and has been thought about and worked for years, however, the return of travel after the pandemic, the progress on L2s and sidechains, and the track record of some stablecoins like DAI have all made it possible to create a fully-functional decentralized accommodation marketplace.
```

2022-06-03 11:12 UTC, ligi approved these changes

2022-06-05 19:30 UTC, rosee8 approved these changes
looking good

2022-06-05 19:32 UTC, merged

2022-06-05 20:30 UTC, lucarioams commented
> looking good

thanks! doesn't seem to have updated automatically on the [website table](https://devcon.org/en/#contribute), do I need to create another PR for that?

2022-06-06 18:25 UTC, rosee8 commented
@ligi Is there a need for another PR?