DIP-17: Make Devcon6 Carbon Neutral
efdevcon/DIPs pull request #79
Opened 2022-06-24 08:51 UTC by danceratopz

Add proposal to make Devcon6 carbon neutral.

2022-06-29 10:20 UTC, rosee8 requested changes
Thanks for this proposal!
Looks great.
One question:
Did I understand correctly that DIP 17 is a part of DIP 1, and focuses on the snapshot voting  to decide upon projects the offsetting funds will be donated to?
If so, can you make this clear in the title? That would be great.

2022-06-29 10:49 UTC, danceratopz commented
> Thanks for this proposal! Looks great. One question: Did I understand correctly that DIP 17 is a part of DIP 1, and focuses on the snapshot voting to decide upon projects the offsetting funds will be donated to? If so, can you make this clear in the title? That would be great.

Hi Rose! I would say this DIP is a stepping stone towards implementing [DIP-1](https://github.com/efdevcon/DIPs/blob/master/DIPs/DIP-1.md). The focus is not really the snapshot voting, rather the focus is the implementation of most components that DIP-1 requires and then directly making use of these components to make Devcon6 carbon neutral in a community-oriented way. 

More concretely, it requires implementing:
- emission estimation for attendee flights (we have already started this work),
- emission estimation for attendee accommodation,
- emission estimation for the event,
- a frontend that allow attendees to (voluntarily) contribute towards offsetting the emissions based on the estimates.

The snapshot voting is then a nice add-on with relatively little overhead to involve the community in the choice of carbon offset project. This was the main aim of [DIP-12](https://github.com/efdevcon/DIPs/blob/master/DIPs/DIP-12.md) as I understand it, but here we don't aim to form a DAO.

What's missing from DIP-1 in DIP-17? DIP-1 aims to integrate the attendee contribution within the Devcon ticketing system, but it's clearly too late to include that step for Devcon6. If we manage to implement the other components for Devcon6, however, we will be very well prepared to integrate it for subsequent events.

Here's a link to the forum discussion:
https://forum.devcon.org/t/lets-make-devcon6-carbon-neutral-a-step-towards-implementing-dip-1-dip-12/400?u=danceratopz 
Perhaps I should add this info there, too.

2022-07-04 10:14 UTC, rosee8 approved these changes

2022-08-18 09:33 UTC, ligi approved these changes
I think this is a great proposal!&Personally think we should to that

2022-08-18 09:35 UTC, merged