Create DIP-17.md
efdevcon/DIPs pull request #81
Opened 2022-06-28 17:43 UTC by costgallo

Create DIP-17.md for hosting DevCon agenda & website on Swarm

2022-06-28 19:37 UTC, danceratopz commented
Hey @costgallo, I saw that you used `DIP-18` within your document, but named the doc itself `DIP-17.md`. Would you mind renaming your `DIP-17.md` to `DIP-18.md`? We also used `DIP-17` in #79. 

If you'd prefer we renamed our DIP instead, just let me know!

Thanks! :pray:

2022-06-29 06:50 UTC, costgallo commented
> Hey @costgallo, I saw that you used `DIP-18` within your document, but named the doc itself `DIP-17.md`. Would you mind renaming your `DIP-17.md` to `DIP-18.md`? We also used `DIP-17` in #79.
> 
> If you'd prefer we renamed our DIP instead, just let me know!
> 
> Thanks! 🙏

Done, thanks!

2022-06-29 09:37 UTC, rosee8 approved these changes
Looks great! We will discuss this with the team asap.

2022-07-11 16:32 UTC, ligi requested changes
Typo - otherwise LGTM

2022-07-11 16:32 UTC, ligi commented on DIPs/DIP-17.md
> +This configuration should be load balanced and supplied with the appropriate postage stamps and chequebook balances. We have experience with how to do this with our gateway website and the underlying
```suggestion
This configuration should be load balanced and supplied with the appropriate postage stamps and chequebook balances. We have experience with how to do this with our gateway website and the underlying infrastructure. We are also in contact with the Ethereum Foundation currently discussing how to set up Swarm nodes for certain Remix IDE services.
```

2022-07-12 08:50 UTC, ligi commented on DIPs/DIP-17.md
> +DIP: DIP-18
```suggestion
DIP: DIP-17
```
must match the filename

2022-08-18 09:52 UTC, ligi requested changes
In general I think it is great! Only 2 nits to remove cruft.
Also the 2 examples do not work for me - this is not really a problem for merging but might be a problem getting this DIP accepted.

2022-08-18 09:52 UTC, ligi commented on DIPs/DIP-17.md
> +__
```suggestion
```

2022-08-18 09:52 UTC, ligi commented on DIPs/DIP-17.md
> +[Bee Documentation](https://docs.ethswarm.org/docs/)__
```suggestion
[Bee Documentation](https://docs.ethswarm.org/docs)
```

2022-08-18 11:19 UTC, ligi commented on DIPs/DIP-18.md
> +__
```suggestion
__
```

2022-08-18 11:19 UTC, ligi requested changes

2022-08-18 11:19 UTC, ligi commented on DIPs/DIP-18.md
> +[Bee Documentation](https://docs.ethswarm.org/docs/)__
```suggestion
[Bee Documentation](https://docs.ethswarm.org/docs/)
```

2022-08-18 11:20 UTC, ligi commented on DIPs/DIP-18.md
> +__
```suggestion
```

2022-08-18 11:31 UTC, ligi commented on DIPs/DIP-18.md
> +DIP: DIP-18
```suggestion
DIP: 18
```

2022-08-18 11:32 UTC, merged

2022-08-19 12:36 UTC, costgallo commented
Thanks for the merge and suggestions, I will make changes in a new PR