Create DIP-X
efdevcon/DIPs pull request #83
Opened 2022-07-31 19:02 UTC by amy-jung

[Waiting on DIP number to be assigned]

This is our DIP for a Design Community Hub. Some of the programming (and therefore programming) are being finalized. Please feel free to reach out with further questions or comments!

2022-08-01 22:31 UTC, ed738 submitted a review, later dismissed

2022-08-18 10:01 UTC, ligi requested changes

2022-08-18 10:39 UTC, ligi commented on DIPs/DIP-22.md
> +DIP: DIP-22
```suggestion
DIP: 22
```

2022-08-18 11:42 UTC, ligi approved these changes

2022-08-18 11:43 UTC, merged

2022-08-18 12:10 UTC, amy-jung commented
Thanks for reviewing and updating @ligi !