DIP-19
efdevcon/DIPs pull request #85
Opened 2022-08-05 09:43 UTC by costgallo

2022-08-05 09:45 UTC, costgallo commented
Created this DIP for hosting DevCon videos archive on Swarm via Etherna in addition to the current offerings

2022-08-05 16:48 UTC, ligi requested changes
Thanks for the proposal - I really like the sentiment - but think in the beginning we need to find an hybrid web2/web3 approach for the website - similar as we do for the videos in the archive

2022-08-05 16:48 UTC, ligi commented on DIPs/DIP-17.md
> +https://fairdataprotocol.bzz.link/
the first one 404s for me - the second one works

2022-08-05 16:48 UTC, ligi commented on DIPs/DIP-17.md
> +https://fairdataprotocol.bzz.link/
![image](https://user-images.githubusercontent.com/111600/183120940-879afb8e-10a8-4710-84c9-31edfffd9539.png)

2022-08-05 16:48 UTC, ligi commented on DIPs/DIP-17.md
> +https://fairdataprotocol.bzz.link/
maybe we should not use the 404ing one as (the first) example then

2022-08-05 16:48 UTC, ligi commented on DIPs/DIP-17.md
> +Provide a DNSLink (optional) so that it can serve regular DNS domains (e.g. devcon.ethereum.org) but still having the data in a format that is compatible with Swarm.
we do things for devcon on devcon.org not ethereum.org

2022-08-18 12:04 UTC, ligi requested changes
Thanks! Great proposal - just small nits
would also be nice to get some more details on the interface to the DEVCon videos / metadata required - could be the start of what I had in mind with a "DEVCon/Event API" a while ago. But we need to know what the interface will be.

2022-08-18 12:04 UTC, ligi commented on DIPs/DIP-19.md
> +
```suggestion
```

2022-08-18 12:47 UTC, ligi commented
can you remove DIP-17 from here? was merged in the other PR

here a sample json: https://ipfs-cluster.ethdevops.io/ipfs/QmQr1GhBMqp6b7zH8ouM9Mkp3nvLDkoMhygGxYrfhB7g7J/Game%20Day%20Remix_berlagezaal_1.json
for the metadata for videos - this could be reused for easier integration - but a good standard/API for this is badly missing.

2022-08-18 12:47 UTC, ligi commented
can you remove DIP-17 from here? was merged in the other PR

here a sample json: https://ipfs-cluster.ethdevops.io/ipfs/QmQr1GhBMqp6b7zH8ouM9Mkp3nvLDkoMhygGxYrfhB7g7J/Game%20Day%20Remix_berlagezaal_1.json
for the metadata for videos - this could be reused for easier integration - but a good standard/API for this is badly missing.

2022-08-26 14:13 UTC, agazso commented
> can you remove DIP-17 from here? was merged in the other PR

Removed the DIP-17, it is now possible to resolve your comments on that file.

2022-08-26 15:11 UTC, ligi approved these changes

2022-08-26 16:09 UTC, ligi commented on DIPs/DIP-19.md
> +DIP: DIP-19
```suggestion
DIP: 19
```

2022-08-26 16:47 UTC, ligi commented on DIPs/DIP-19.md
> +Discussion: https://forum.devcon.org/t/host-devcon-videos-on-swarm-etherna/585/6
```suggestion
Discussion: https://forum.devcon.org/t/host-devcon-videos-on-swarm-etherna/585/6
Created: 2023-08-26
```

2022-08-26 17:01 UTC, ligi requested changes
Small typos

2022-08-26 17:01 UTC, ligi commented on DIPs/DIP-19.md
> +More tests have to been done, and probably a gateway component (interceptor) will need to be rewrited with a different technology (migrate from Nginx to a reverse proxy implemented with .Net). Anyway
```suggestion
More tests have to been done, and probably a gateway component (interceptor) will need to be rewritten with a different technology (migrate from Nginx to a reverse proxy implemented with .Net). Anyway in this phase videos are still manually encoded, and compression can be adjusted accordingly.
```

2022-08-29 12:55 UTC, ligi approved these changes

2022-08-29 12:55 UTC, merged

2024-02-02 16:16 UTC, tmm360 commented
Hello everyone, as Etherna we would like to provide video hosting based on Swarm also for Devcon VII, with improved tools and infrastructure!