Create ZK_Community_Hub
efdevcon/DIPs pull request #99
Opened 2022-09-13 02:06 UTC by emchoos

Hello!

Sorry for the delay. Our approved community hub post is here: https://forum.devcon.org/t/community-hub-proposal-zk-community-hub/773

Please let us know if there is anything we need to change, and we look forward to seeing you in person soon!

2022-09-29 13:02 UTC, franzihei requested changes
Two small things, otherwise looks great from my side!

2022-09-29 13:02 UTC, franzihei commented on ZK_Community_Hub
> +Tags: Event Production
```suggestion
Tags: Community Hub, Event Production
```

2022-09-29 13:02 UTC, franzihei commented on ZK_Community_Hub
> +Resources Required: Seating for discussion groups, TV-sized screen, Power Outlets, Signage, Desks and tables, Whiteboards
```suggestion
Resources Required: Seating for discussion groups, TV-sized screen, Power Outlet, Signage, Desks and tables, Whiteboard
```

Note that the Community Hub production guideline only includes one power outlet and one whiteboard. If you need more, please bring it! We recommend bringing extension cords / multi-plugs!

2022-10-09 17:44 UTC, ligi requested changes

2022-10-09 17:44 UTC, ligi commented on ZK_Community_Hub
> +__Simple Summary__
```suggestion
## Summary of Proposal

```

2022-10-09 17:44 UTC, ligi commented on ZK_Community_Hub
> +-----Abstract-----
```suggestion
## Abstract
```

2022-10-09 17:44 UTC, ligi commented on ZK_Community_Hub
> +-----Motivation & Rationale-----
```suggestion
## Motivation & Rationale
```

2022-10-09 17:44 UTC, ligi commented on ZK_Community_Hub
> +-----Implementation-----
```suggestion
## Implementation
```

2022-10-09 17:44 UTC, ligi commented on ZK_Community_Hub
> +-----Operational Requirements & Ownership-----
```suggestion
## Operational Requirements & Ownership
```

2022-10-09 17:44 UTC, ligi commented on ZK_Community_Hub
> +__Please answer questions below:__
```suggestion

```

2022-10-09 17:44 UTC, ligi commented on ZK_Community_Hub
> +-----Links & Additional Information-----
```suggestion
```

2022-10-09 17:47 UTC, ligi commented on ZK_Community_Hub
> +DIP: TBD
```suggestion
DIP: 28
```

2022-10-09 18:25 UTC, merged